web:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3005:3005"
  links:
    - "db"

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
    - ./pgdata:/var/lib/postgresql/data
    - ./db/initdb.d:/docker-entrypoint-initdb.d
  ports:
    - "5432:5432"
